version: '3.3'

services: 

  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    depends_on: 
      - mongodb

  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    depends_on:
      - salt-master

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
